In [1]:
import numpy as np
import xgboost as xgb
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#df = pd.read_pickle('C:/Users/amaca253/Desktop/Friends-Friends-Language-Analysis/BBT/data_emb.pkl')
pca_df = pd.read_pickle('C:/Users/amaca253/Desktop/Friends-Friends-Language-Analysis/BBT/data_300pca.pkl')
#pca_df = pd.read_pickle('C:/Users/amaca253/Desktop/Friends-Friends-Language-Analysis/data_pickle/all_sentences_pca.pkl')

In [ ]:
print(pca_df)

In [2]:
X = pca_df.loc[:,'PCA1':'PCA20']
X = X.values
one_hot = pd.get_dummies(pca_df['Person'])
y = one_hot.values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state = 0)

In [3]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = pca_df['Person']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['Sheldon' 'Leonard' 'Sheldon' ... 'Sheldon' 'Sheldon' 'Sheldon']
[6 3 6 ... 6 6 6]
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
['Sheldon']


In [4]:
from xgboost import XGBClassifier
xgb_model= xgb.XGBRegressor(max_depth=7,
    n_estimators=100, learning_rate=0.44,
    subsample = 0.25).fit(
    X_train, y_train)
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
pred = xgb_model.predict(X_test)
y_pred = np.argmax(pred, axis=1)
y_test2 = np.argmax(y_test, axis=1)
# evaluate predictions

accuracy = accuracy_score(y_test2, y_pred)
print("Accuracy:", (accuracy * 100.0))

# max_depth=7, n_estimators=100, learning_rate=0.44, subsample = 0.25, test size = 1/4
# for 300PCA: Accuracy: 22.157979007294077
# for 30 PCA : Accuracy: 22.878491371642056
# for 25 PCA: 22.825120085394058
# for 20 PCA: accuracy = 23.572318092866038
# for 15 PCA: accuracy = Accuracy: 22.513787582280735
# for 10 PCA: accuracy = 21.92670343355275
# for 2 PCA: 22.56715886852873

In [ ]:
# import matplotlib.pyplot as plt
y_acc = [22.56715886852873, 21.92670343355275, 22.513787582280735, 23.572318092866038, 22.825120085394058, 22.878491371642056, 22.157979007294077]
x_acc = [2, 10, 15, 20, 25, 30, 300]

plt.figure()
plt.plot(x_acc,y_acc)
plt.xlabel('Number of PCA')
plt.ylabel('Accuracy')
plt.show()

In [ ]:
for i in np.arange(len(y_test)):
    print(label_encoder.inverse_transform([argmax(y_test[i, :])]),'prediction:', label_encoder.inverse_transform([argmax(pred[i, :])]))